CREATE TABLE IF NOT EXISTS "iot_event" (
  "iot_event_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "device_id" varchar(50),
  "event_data" varchar(1000),
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);